### ISSUE TITLE
[功能申请] 允许手势导航下打开快速搜索菜单

### ISSUE THREAD

**Issue by duzhaokun123** [NekoInverter/EhViewer#17]
**这个功能是用来解决问题的吗？**
使用手势导航时无法打开快速搜索菜单

**描述你想要的解决方法**
增加按钮用于打开快速搜索菜单或实现旧的在中间滑动打开抽屉

**Comment by NekoInverter** [comment]
可以打开

**Comment by duzhaokun123** [comment]
链接:https://pan.baidu.com/s/1Cx2qkd7OSVkIqBXdxfhLCA 提取码:73j0

你能打开不代表所有人都能打开，比如我用 Lineage OS 17.1 就不行

**Comment by NekoInverter** [comment]
问你系统维护者，原生 Android 没有问题

**Comment by NekoInverter** [comment]
#3

**Comment by LawdStalker** [comment]
In version 1.7.3 it was much easier to open the side drawers, using the left/right swipe gesture from the middle of the screen instead of the edges.

Has this been changed because of a design choice (to keep the default android behavior or something like that) or just regular changes from android libraries?
Because personally I think the previous behavior was more practical.

**Comment by NekoInverter** [comment]
> In version 1.7.3 it was much easier to open the side drawers, using the left/right swipe gesture from the middle of the screen instead of the edges.
> 
> Has this been changed because of a design choice (to keep the default android behavior or something like that) or just regular changes from android libraries?
> Because personally I think the previous behavior was more practical.

It's google's official drawer library behavior
